import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import clsx from "clsx";
import Footer from "./components/Footer/Footer";
import Welcome from "./home/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'container mx-[auto] my-0 font-cera-pro')}>
        <Navbar />
        <main>
        </main>
        {children}</body>
    </html >
  );
}
